CREATE TABLE user(
  id  INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  payload TEXT NOT NULL
);

CREATE TABLE center(
  id  INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  cp INTEGER NOT NULL,
  phone INTEGER NOT NULL,
  max_capacity  INTEGER NOT NULL,
  user_id INTEGER,
  FOREIGN KEY(user_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE animal(
  id  INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  age INTEGER NOT NULL,
  center_id INTEGER,
  user_id INTEGER,
  FOREIGN KEY(center_id) REFERENCES Center(id) ON DELETE CASCADE,
  FOREIGN KEY(user_id) REFERENCES User(id) ON DELETE CASCADE
);
